repositories:
  - name: istio
    url: https://istio-release.storage.googleapis.com/charts
  - name: prometheus-community
    url: https://prometheus-community.github.io/helm-charts
  - name: kiali
    url: https://kiali.org/helm-charts
  - name: jaegertracing
    url: https://jaegertracing.github.io/helm-charts
  - name: grafana
    url: https://grafana.github.io/helm-charts

releases:
  - name: istio-base
    namespace: istio-system
    createNamespace: true
    chart: istio/base
    version: 1.20.0
    wait: true

  - name: istiod
    namespace: istio-system
    chart: istio/istiod
    version: 1.20.0
    needs:
      - istio-system/istio-base
    wait: true
    values:
      - istio/istiod-values.yaml

  - name: istio-ingress
    namespace: istio-system
    chart: istio/gateway
    version: 1.20.0
    needs:
      - istio-system/istiod
    wait: false
    set:
      - name: labels.istio
        value: ingressgateway
      - name: labels.app
        value: istio-ingressgateway
      - name: service.type
        value: LoadBalancer

  - name: kiali
    namespace: istio-system
    chart: kiali/kiali-server
    version: 1.78.0
    needs:
      - istio-system/istiod
    wait: false
    values:
      - istio/kiali-values.yaml

  - name: prometheus
    namespace: istio-system
    chart: prometheus-community/kube-prometheus-stack
    needs:
      - istio-system/istiod
    wait: false
    values:
      - istio/prometheus-values.yaml

  - name: jaeger
    namespace: istio-system
    chart: jaegertracing/jaeger
    wait: false

  - name: loki
    namespace: istio-system
    createNamespace: false
    chart: grafana/loki
    needs:
      - istio-system/istiod
    wait: false
    values:
      - istio/loki-values.yaml

  - name: promtail
    namespace: istio-system
    createNamespace: false
    chart: grafana/promtail
    needs:
      - istio-system/loki
    wait: false
    values:
      - istio/promtail-values.yaml

  - name: istio-config
    namespace: muffin-services
    createNamespace: true
    chart: ./istio-config
    needs:
      - istio-system/istiod
      - istio-system/prometheus
    values:
      - istio-config/values.yaml

  - name: muffin-currency
    namespace: muffin-services
    createNamespace: false
    chart: ./muffin-currency
    needs:
      - istio-system/istiod
      - muffin-services/istio-config
    values:
      - muffin-currency/values.yaml

  - name: muffin-wallet
    namespace: muffin-services
    createNamespace: false
    chart: ./muffin-wallet
    needs:
      - muffin-services/muffin-currency
      - muffin-services/istio-config
    values:
      - muffin-wallet/values.yaml

