---
apiVersion: v1
kind: Service
metadata:
  name: muffin-postgres
  namespace: muffin-services
spec:
  type: ClusterIP
  selector:
    app: muffin-postgres
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init-script
  namespace: muffin-services
data:
  01-init-extensions.sql: |
    -- Enable required PostgreSQL extensions
    CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: muffin-postgres
  namespace: muffin-services
  labels:
    app: muffin-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: muffin-postgres
  template:
    metadata:
      labels:
        app: muffin-postgres
    spec:
      containers:
        - name: postgres
          image: postgres:15
          env:
            - name: POSTGRES_DB
              value: muffin_wallet
            - name: POSTGRES_USER
              value: muffin-wallet
            - name: POSTGRES_PASSWORD
              value: muffin-wallet
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
            - name: postgres-init
              mountPath: /docker-entrypoint-initdb.d
      volumes:
        - name: postgres-data
          emptyDir: {}
        - name: postgres-init
          configMap:
            name: postgres-init-script
