{{- if .Values.ingress.enabled }}
{{- if .Values.ingress.tls.enabled }}
{{- if and .Values.ingress.tls.certificate .Values.ingress.tls.key }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "muffin-wallet.resource-name" . }}-tls
  labels:
    {{ include "muffin-wallet.labels" . | nindent 4 }}
type: kubernetes.io/tls
data:
  tls.crt: {{ .Values.ingress.tls.certificate }}
  tls.key: {{ .Values.ingress.tls.key }}
{{- end }}
{{- end }}
{{- end }}
