{{- if .Values.peerAuthentication.enabled }}
apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: default
  namespace: muffin-services
spec:
  mtls:
    mode: STRICT
{{- end }}
