{{- if .Values.prometheus.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: muffin-wallet
  namespace: istio-system
  labels:
    release: prometheus
spec:
  namespaceSelector:
    matchNames:
      - muffin-services
  selector:
    matchLabels:
      app: muffin-wallet
  endpoints:
    - targetPort: 8081
      path: /actuator/prometheus
      interval: 15s
{{- end }}
