{{- if .Values.serviceEntry.postgres.enabled }}
apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: muffin-postgres
  namespace: muffin-services
spec:
  hosts:
    - {{ .Values.serviceEntry.postgres.host | default "host.docker.internal" }}
  {{- if .Values.serviceEntry.postgres.address }}
  addresses:
    - {{ .Values.serviceEntry.postgres.address }}
  {{- end }}
  ports:
    - number: {{ .Values.serviceEntry.postgres.port | default 5432 }}
      name: postgres
      protocol: TCP
  location: MESH_EXTERNAL
  resolution: {{ .Values.serviceEntry.postgres.resolution | default "DNS" }}
{{- end }}
