{{- if .Values.virtualServices.currency.enabled }}
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: muffin-currency
  namespace: muffin-services
spec:
  hosts:
    - muffin-currency
  http:
    - match:
        - uri:
            prefix: /rate
      route:
        - destination:
            host: muffin-currency
            port:
              number: 8083
          weight: 100
      timeout: 10s
      retries:
        attempts: 2
        perTryTimeout: 5s
        retryOn: 5xx,reset,connect-failure
{{- end }}
